---
abstract: 'This module tries to convert a number into Chinese cardinal number. It supports decimals number, and five representation systems (charsets): traditional, simplified, big5, gb and pinyin.'
author:
  - 'Autrijus Tang <autrijus@autrijus.org>'
build_requires:
  Test::More: 0
  utf8: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-ZHO-Numbers
requires:
  Exporter: 0
  base: 0
  perl: 5.001
  strict: 0
  vars: 0
version: 0.044
